### ISSUE TITLE
some random feedback 

### ISSUE THREAD

**Issue by dogfrogfog** [YourunB/graphiql-app#23]
- судя по всему страница грузится 2 раза когда меняешь язык 
- gql лого обрезано
- gql лого не заблюрено, может быть сложно читать текст
- странно грузится страница при логине, такое чувство что все меняется 2-3 раза
- хоть эндпоинт и вписывается на клиенте в ручную, в другой ситуации его лучше не  экспоузить (use server actions instead)

https://github.com/user-attachments/assets/3198cc0f-e686-418f-947a-0e47fb45f22a

<img width="738" alt="Screenshot 2024-09-22 at 10 59 21" src="https://github.com/user-attachments/assets/c10eb08c-60bc-4dbb-8edb-32b37d0182ed">
<img width="1469" alt="Screenshot 2024-09-22 at 11 04 40" src="https://github.com/user-attachments/assets/50d30061-2751-42de-a450-61f375051867">

https://github.com/user-attachments/assets/fe65d8a8-8a86-4046-b134-278771143d70

**Comment by YourunB** [comment]
Спасибо за отзыв ) Нет предела совершенству. Задача выполнялась в сжатые сроки и изначально незнакомой командой в соответствии с ТЗ. Честно говоря, есть много мыслей о том, как и где улучшить приложение. Тут вопрос времени и целесообразности. Проект учебный.
